services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.test
  node_app:
    container_name: node_app
    build: .
    ports:
    - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - .env.test
