name: "PullRequest"
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubunto-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "students-test"
          envkey_DATABASE_URL: "DATABASE_URL=postgresql://postgres:postgres_db:5432/students-test"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test
      - name: Build
        run: npm i && npm run build